packages:
  - 'packages/*'
  - scripts
  - docs

# Define a catalog of version ranges.
catalog:
  '@types/react': 18.3.12
  '@types/react-dom': 18.3.1
  '@babel/runtime': 7.26.0
  '@babel/core': 7.24.7
  react: 18.2.0
  react-dom: 18.2.0
  vite: 5.4.10
